services:
  master-app:
    build:
      context: .
      dockerfile: apps/master/Dockerfile
    container_name: inops-master-app
    ports:
      - "3001:3001"  # Map container port 3001 to host port 3001
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3001
      # Public API URLs (safe to expose)
      - NEXT_PUBLIC_API_BASE_URL=http://192.168.71.20:8000
      # Application settings
      - APP_NAME=INops Master App
      - APP_VERSION=1.0.0
      # Additional environment variables
      - NEXTAUTH_SECRET=your-nextauth-secret-here
      - NEXTAUTH_URL=http://localhost:3000
      - CORS_ORIGIN=http://localhost:3000
    env_file:
      - ./config/app.env  # For non-sensitive configuration
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/master/api/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    networks:
      - inops-network
    volumes:
      - app-logs:/app/logs  # Persistent logs

volumes:
  app-logs:
    driver: local

networks:
  inops-network:
    external: true 