services:
  leave-app:
    build:
      context: .
      dockerfile: apps/leave/Dockerfile
    container_name: inops-leave-app
    ports:
      - "3005:3005"  # Map container port 3005 to host port 3006
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3005
      - NEXT_PUBLIC_API_BASE_URL=http://192.168.71.20:8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3005/leave/api/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    networks:
      - inops-network

networks:
  inops-network:
    external: true 