interface Contact {
    id: number;
    name: string;
    date: string;
    phone: string;
    email: string;
    type: string;
    image: string;
  }
  export const contacts: Contact[] = [
    {
      id: 1,
      name: "Esther Howard",
      date: "Jan 5, 2021",
      phone: "(555) 123-4567",
      email: "john@gmail.com",
      type: "Partnership",
      image: "",
    },
    {
      id: 2,
      name: "Jerome Bell",
      date: "Jan 5, 2021",
      phone: "(555) 123-4567",
      email: "john@gmail.com",
      type: "Partnership",
      image: "",
    },
    {
      id: 3,
      name: "Darlene Robertson",
      date: "Jan 5, 2021",
      phone: "(555) 123-4567",
      email: "john@gmail.com",
      type: "Partnership",
      image: "",
    },
    {
      id: 4,
      name: "Brooklyn Simmons",
      date: "Jan 5, 2021",
      phone: "(555) 123-4567",
      email: "john@gmail.com",
      type: "Partnership",
      image: "",
    },
    {
      id: 5,
      name: "Cody Fisher",
      date: "Jan 5, 2021",
      phone: "(555) 123-4567",
      email: "john@gmail.com",
      type: "Partnership",
      image: "",
    },
    {
      id: 6,
      name: "Dianne Russell",
      date: "Jan 5, 2021",
      phone: "(555) 123-4567",
      email: "john@gmail.com",
      type: "Partnership",
      image: "",
    },
    {
      id: 7,
      name: "Marvin McKinney",
      date: "Jan 5, 2021",
      phone: "(555) 123-4567",
      email: "john@gmail.com",
      type: "Partnership",
      image: "",
    },
    {
      id: 8,
      name: "Jenny Wilson",
      date: "Jan 5, 2021",
      phone: "(555) 123-4567",
      email: "john@gmail.com",
      type: "Partnership",
      image: "",
    },
    {
      id: 9,
      name: "Arlene McCoy",
      date: "Jan 5, 2021",
      phone: "(555) 123-4567",
      email: "john@gmail.com",
      type: "Partnership",
      image: "",
    },
  ];

  export const namefilteroption = [
    { value: "vinayak", label: "Vinayak" },
    { value: "vinay", label: "Vinay" },
    { value: "vijay", label: "Vijay" },
    { value: "arjun", label: "Arjun" },
    { value: "rahul", label: "Rahul" },
    { value: "rohit", label: "Rohit" },
    { value: "suresh", label: "Suresh" },
    { value: "mahesh", label: "Mahesh" },
    { value: "raj", label: "Raj" },
    { value: "deepak", label: "Deepak" },
    { value: "manoj", label: "Manoj" },
    { value: "amit", label: "Amit" },
    { value: "ankit", label: "Ankit" },
    { value: "ravi", label: "Ravi" },
    { value: "kiran", label: "Kiran" },
    { value: "sunil", label: "Sunil" },
    { value: "sachin", label: "Sachin" },
    { value: "dev", label: "Dev" },
    { value: "suraj", label: "Suraj" },
    { value: "yash", label: "Yash" },
    { value: "pranav", label: "Pranav" },
    { value: "tejas", label: "Tejas" },
    { value: "anil", label: "Anil" },
    { value: "ashok", label: "Ashok" },
    { value: "naveen", label: "Naveen" },
    { value: "lokesh", label: "Lokesh" },
    { value: "shyam", label: "Shyam" },
    { value: "harsh", label: "Harsh" },
    { value: "vivek", label: "Vivek" },
    { value: "girish", label: "Girish" },
    { value: "rakesh", label: "Rakesh" },
    { value: "dinesh", label: "Dinesh" },
    { value: "mukesh", label: "Mukesh" },
    { value: "sanjay", label: "Sanjay" },
    { value: "abhishek", label: "Abhishek" },
    { value: "anurag", label: "Anurag" },
    { value: "tarun", label: "Tarun" },
    { value: "mayur", label: "Mayur" },
    { value: "rishi", label: "Rishi" },
    { value: "shubham", label: "Shubham" },
    { value: "gaurav", label: "Gaurav" },
    { value: "nikhil", label: "Nikhil" },
    { value: "bhavesh", label: "Bhavesh" },
    { value: "jitesh", label: "Jitesh" },
    { value: "kamal", label: "Kamal" },
    { value: "lalit", label: "Lalit" },
    { value: "varun", label: "Varun" },
    { value: "harshit", label: "Harshit" },
    { value: "parth", label: "Parth" },
    { value: "vishal", label: "Vishal" },
    { value: "rajesh", label: "Rajesh" },
    { value: "siddharth", label: "Siddharth" },
    { value: "utkarsh", label: "Utkarsh" },
    { value: "puneet", label: "Puneet" },
    { value: "avinash", label: "Avinash" },
    { value: "aditya", label: "Aditya" },
    { value: "anuradha", label: "Anuradha" },
    { value: "neha", label: "Neha" },
    { value: "pooja", label: "Pooja" },
    { value: "swati", label: "Swati" },
    { value: "priya", label: "Priya" },
    { value: "kavita", label: "Kavita" },
    { value: "rekha", label: "Rekha" },
    { value: "lata", label: "Lata" },
    { value: "anita", label: "Anita" },
    { value: "meena", label: "Meena" },
    { value: "geeta", label: "Geeta" },
    { value: "usha", label: "Usha" },
    { value: "seema", label: "Seema" },
    { value: "jyoti", label: "Jyoti" },
    { value: "suman", label: "Suman" },
    { value: "archana", label: "Archana" },
    { value: "sneha", label: "Sneha" },
    { value: "shruti", label: "Shruti" },
    { value: "aarti", label: "Aarti" },
    { value: "nisha", label: "Nisha" },
    { value: "payal", label: "Payal" },
    { value: "sonali", label: "Sonali" },
    { value: "radhika", label: "Radhika" },
    { value: "divya", label: "Divya" },
    { value: "madhuri", label: "Madhuri" },
    { value: "bhavana", label: "Bhavana" },
    { value: "shraddha", label: "Shraddha" },
    { value: "tanvi", label: "Tanvi" },
    { value: "nikita", label: "Nikita" },
    { value: "karishma", label: "Karishma" },
    { value: "trisha", label: "Trisha" },
    { value: "kanika", label: "Kanika" },
    { value: "isha", label: "Isha" },
    { value: "aishwarya", label: "Aishwarya" },
    { value: "sanjana", label: "Sanjana" },
    { value: "tanya", label: "Tanya" },
    { value: "megha", label: "Megha" },
    { value: "namrata", label: "Namrata" },
    { value: "rani", label: "Rani" },
    { value: "pranita", label: "Pranita" },
    { value: "bhavya", label: "Bhavya" },
    { value: "kiranmayi", label: "Kiranmayi" },
    { value: "lavanya", label: "Lavanya" },
    { value: "vidya", label: "Vidya" },
  ];


  export const emailFilterOption = [
    { value: "vinayak@example.com", label: "vinayak@example.com" },
    { value: "vinay@example.com", label: "vinay@example.com" },
    { value: "vijay@example.com", label: "vijay@example.com" },
    { value: "arjun@example.com", label: "arjun@example.com" },
    { value: "rahul@example.com", label: "rahul@example.com" },
    { value: "rohit@example.com", label: "rohit@example.com" },
    { value: "suresh@example.com", label: "suresh@example.com" },
    { value: "mahesh@example.com", label: "mahesh@example.com" },
    { value: "raj@example.com", label: "raj@example.com" },
    { value: "deepak@example.com", label: "deepak@example.com" },
    { value: "manoj@example.com", label: "manoj@example.com" },
    { value: "amit@example.com", label: "amit@example.com" },
    { value: "ankit@example.com", label: "ankit@example.com" },
    { value: "ravi@example.com", label: "ravi@example.com" },
    { value: "kiran@example.com", label: "kiran@example.com" },
    { value: "sunil@example.com", label: "sunil@example.com" },
    { value: "sachin@example.com", label: "sachin@example.com" },
    { value: "dev@example.com", label: "dev@example.com" },
    { value: "suraj@example.com", label: "suraj@example.com" },
    { value: "yash@example.com", label: "yash@example.com" },
    { value: "pranav@example.com", label: "pranav@example.com" },
    { value: "tejas@example.com", label: "tejas@example.com" },
    { value: "anil@example.com", label: "anil@example.com" },
    { value: "ashok@example.com", label: "ashok@example.com" },
    { value: "naveen@example.com", label: "naveen@example.com" },
    { value: "lokesh@example.com", label: "lokesh@example.com" },
    { value: "shyam@example.com", label: "shyam@example.com" },
    { value: "harsh@example.com", label: "harsh@example.com" },
    { value: "vivek@example.com", label: "vivek@example.com" },
    { value: "girish@example.com", label: "girish@example.com" },
    { value: "rakesh@example.com", label: "rakesh@example.com" },
    { value: "dinesh@example.com", label: "dinesh@example.com" },
    { value: "mukesh@example.com", label: "mukesh@example.com" },
    { value: "sanjay@example.com", label: "sanjay@example.com" },
    { value: "abhishek@example.com", label: "abhishek@example.com" },
    { value: "anurag@example.com", label: "anurag@example.com" },
    { value: "tarun@example.com", label: "tarun@example.com" },
    { value: "mayur@example.com", label: "mayur@example.com" },
    { value: "rishi@example.com", label: "rishi@example.com" },
    { value: "shubham@example.com", label: "shubham@example.com" },
    { value: "gaurav@example.com", label: "gaurav@example.com" },
    { value: "nikhil@example.com", label: "nikhil@example.com" },
    { value: "bhavesh@example.com", label: "bhavesh@example.com" },
    { value: "jitesh@example.com", label: "jitesh@example.com" },
    { value: "kamal@example.com", label: "kamal@example.com" },
    { value: "lalit@example.com", label: "lalit@example.com" },
    { value: "varun@example.com", label: "varun@example.com" },
    { value: "harshit@example.com", label: "harshit@example.com" },
    { value: "parth@example.com", label: "parth@example.com" },
    { value: "vishal@example.com", label: "vishal@example.com" },
    { value: "rajesh@example.com", label: "rajesh@example.com" },
    { value: "siddharth@example.com", label: "siddharth@example.com" },
    { value: "utkarsh@example.com", label: "utkarsh@example.com" },
    { value: "puneet@example.com", label: "puneet@example.com" },
    { value: "avinash@example.com", label: "avinash@example.com" },
    { value: "aditya@example.com", label: "aditya@example.com" },
    { value: "anuradha@example.com", label: "anuradha@example.com" },
    { value: "neha@example.com", label: "neha@example.com" },
    { value: "pooja@example.com", label: "pooja@example.com" },
    { value: "swati@example.com", label: "swati@example.com" },
    { value: "priya@example.com", label: "priya@example.com" },
    { value: "kavita@example.com", label: "kavita@example.com" },
    { value: "rekha@example.com", label: "rekha@example.com" },
    { value: "lata@example.com", label: "lata@example.com" },
    { value: "anita@example.com", label: "anita@example.com" },
    { value: "meena@example.com", label: "meena@example.com" },
    { value: "geeta@example.com", label: "geeta@example.com" },
    { value: "usha@example.com", label: "usha@example.com" },
    { value: "seema@example.com", label: "seema@example.com" },
    { value: "jyoti@example.com", label: "jyoti@example.com" },
    { value: "suman@example.com", label: "suman@example.com" },
    { value: "archana@example.com", label: "archana@example.com" },
    { value: "sneha@example.com", label: "sneha@example.com" },
    { value: "shruti@example.com", label: "shruti@example.com" },
    { value: "aarti@example.com", label: "aarti@example.com" },
    { value: "nisha@example.com", label: "nisha@example.com" },
    { value: "payal@example.com", label: "payal@example.com" },
    { value: "sonali@example.com", label: "sonali@example.com" },
    { value: "radhika@example.com", label: "radhika@example.com" },
    { value: "divya@example.com", label: "divya@example.com" },
    { value: "madhuri@example.com", label: "madhuri@example.com" },
    { value: "bhavana@example.com", label: "bhavana@example.com" },
    { value: "shraddha@example.com", label: "shraddha@example.com" },
    { value: "tanvi@example.com", label: "tanvi@example.com" },
    { value: "nikita@example.com", label: "nikita@example.com" },
    { value: "karishma@example.com", label: "karishma@example.com" },
    { value: "trisha@example.com", label: "trisha@example.com" },
    { value: "kanika@example.com", label: "kanika@example.com" },
    { value: "isha@example.com", label: "isha@example.com" },
    { value: "aishwarya@example.com", label: "aishwarya@example.com" },
    { value: "sanjana@example.com", label: "sanjana@example.com" },
    { value: "tanya@example.com", label: "tanya@example.com" },
    { value: "megha@example.com", label: "megha@example.com" },
    { value: "namrata@example.com", label: "namrata@example.com" },
    { value: "rani@example.com", label: "rani@example.com" },
    { value: "pranita@example.com", label: "pranita@example.com" },
    { value: "bhavya@example.com", label: "bhavya@example.com" },
    { value: "kiranmayi@example.com", label: "kiranmayi@example.com" },
    { value: "lavanya@example.com", label: "lavanya@example.com" },
    { value: "vidya@example.com", label: "vidya@example.com" },
  ];

  export const empIdFilterOption = [
    { value: "EMP001", label: "EMP001" },
    { value: "EMP002", label: "EMP002" },
    { value: "EMP003", label: "EMP003" },
    { value: "EMP004", label: "EMP004" },
    { value: "EMP005", label: "EMP005" },
    { value: "EMP006", label: "EMP006" },
    { value: "EMP007", label: "EMP007" },
    { value: "EMP008", label: "EMP008" },
    { value: "EMP009", label: "EMP009" },
    { value: "EMP010", label: "EMP010" },
    { value: "EMP011", label: "EMP011" },
    { value: "EMP012", label: "EMP012" },
    { value: "EMP013", label: "EMP013" },
    { value: "EMP014", label: "EMP014" },
    { value: "EMP015", label: "EMP015" },
    { value: "EMP016", label: "EMP016" },
    { value: "EMP017", label: "EMP017" },
    { value: "EMP018", label: "EMP018" },
    { value: "EMP019", label: "EMP019" },
    { value: "EMP020", label: "EMP020" },
    { value: "EMP021", label: "EMP021" },
    { value: "EMP022", label: "EMP022" },
    { value: "EMP023", label: "EMP023" },
    { value: "EMP024", label: "EMP024" },
    { value: "EMP025", label: "EMP025" },
    { value: "EMP026", label: "EMP026" },
    { value: "EMP027", label: "EMP027" },
    { value: "EMP028", label: "EMP028" },
    { value: "EMP029", label: "EMP029" },
    { value: "EMP030", label: "EMP030" },
    { value: "EMP031", label: "EMP031" },
    { value: "EMP032", label: "EMP032" },
    { value: "EMP033", label: "EMP033" },
    { value: "EMP034", label: "EMP034" },
    { value: "EMP035", label: "EMP035" },
    { value: "EMP036", label: "EMP036" },
    { value: "EMP037", label: "EMP037" },
    { value: "EMP038", label: "EMP038" },
    { value: "EMP039", label: "EMP039" },
    { value: "EMP040", label: "EMP040" },
    { value: "EMP041", label: "EMP041" },
    { value: "EMP042", label: "EMP042" },
    { value: "EMP043", label: "EMP043" },
    { value: "EMP044", label: "EMP044" },
    { value: "EMP045", label: "EMP045" },
    { value: "EMP046", label: "EMP046" },
    { value: "EMP047", label: "EMP047" },
    { value: "EMP048", label: "EMP048" },
    { value: "EMP049", label: "EMP049" },
    { value: "EMP050", label: "EMP050" },
    { value: "EMP051", label: "EMP051" },
    { value: "EMP052", label: "EMP052" },
    { value: "EMP053", label: "EMP053" },
    { value: "EMP054", label: "EMP054" },
    { value: "EMP055", label: "EMP055" },
    { value: "EMP056", label: "EMP056" },
    { value: "EMP057", label: "EMP057" },
    { value: "EMP058", label: "EMP058" },
    { value: "EMP059", label: "EMP059" },
    { value: "EMP060", label: "EMP060" },
    { value: "EMP061", label: "EMP061" },
    { value: "EMP062", label: "EMP062" },
    { value: "EMP063", label: "EMP063" },
    { value: "EMP064", label: "EMP064" },
    { value: "EMP065", label: "EMP065" },
    { value: "EMP066", label: "EMP066" },
    { value: "EMP067", label: "EMP067" },
    { value: "EMP068", label: "EMP068" },
    { value: "EMP069", label: "EMP069" },
    { value: "EMP070", label: "EMP070" },
    { value: "EMP071", label: "EMP071" },
    { value: "EMP072", label: "EMP072" },
    { value: "EMP073", label: "EMP073" },
    { value: "EMP074", label: "EMP074" },
    { value: "EMP075", label: "EMP075" },
    { value: "EMP076", label: "EMP076" },
    { value: "EMP077", label: "EMP077" },
    { value: "EMP078", label: "EMP078" },
    { value: "EMP079", label: "EMP079" },
    { value: "EMP080", label: "EMP080" },
    { value: "EMP081", label: "EMP081" },
    { value: "EMP082", label: "EMP082" },
    { value: "EMP083", label: "EMP083" },
    { value: "EMP084", label: "EMP084" },
    { value: "EMP085", label: "EMP085" },
    { value: "EMP086", label: "EMP086" },
    { value: "EMP087", label: "EMP087" },
    { value: "EMP088", label: "EMP088" },
    { value: "EMP089", label: "EMP089" },
    { value: "EMP090", label: "EMP090" },
    { value: "EMP091", label: "EMP091" },
    { value: "EMP092", label: "EMP092" },
    { value: "EMP093", label: "EMP093" },
    { value: "EMP094", label: "EMP094" },
    { value: "EMP095", label: "EMP095" },
    { value: "EMP096", label: "EMP096" },
    { value: "EMP097", label: "EMP097" },
    { value: "EMP098", label: "EMP098" },
    { value: "EMP099", label: "EMP099" },
    { value: "EMP100", label: "EMP100" },
  ];
  
  
  