import { act } from "react";

export const stepcontractoremployee = {
  component: "form",
  mode: "view",
  title: "",
  name: "one",
  description: "",
  classvalue: "grid-cols-12",
  baseurl: "api/sectiondetails",
  subformstructure: [
    {
      formgrid: 1,
      title: "Step By Step Selection",
      classvalue: "col-span-12 gap-4",
      validationRules: {
        required: [
          "code",
          "birth_date",
          "father_name",
          "owner_name",
          "owner_contact_no",
          "owner_email",
          "contact_person_name",
          "contact_person_contact_no",
          "contact_person_email",
          "type_of_company",
          "area_of_work",
          "service_from",
          "service_end",
          "name",
        ],
      },
      fields: [
        {
          type: "selectinput",
          tag: "selectinput",
          label: "Organization*",
          name: "organization",
          icon: "building",
          mode: "super-edit",
          value: "",
          classvalue: {
            container: "col-span-12",
            label: "text-gray-600",
            field: "p-2",
          },
          required: true,
          options: [
            { label: "Construction", value: "Construction" },
            { label: "IT Services", value: "IT Services" },
            { label: "Manufacturing", value: "Manufacturing" },
            { label: "Education", value: "Education" },
            { label: "Healthcare", value: "Healthcare" },
          ],
          onChange: [
            {
              event: "updatechild",
            },
          ],
          fieldGrid: 1,
          displayOrder: 1,
          children: ["location"],
        },
        {
          type: "selectinput",
          tag: "selectinput",
          label: "Location",
          name: "location",
          value: "",
          classvalue: {
            container: "col-span-12",
            label: "text-gray-600",
            field: "p-2",
          },
          required: true,
          mode: "view",
          options: [],
          onChange: [
            {
              event: "updatechild",
            },
          ],
          fieldGrid: 1,
          displayOrder: 2, // Function to fetch departments based on division
          children: ["subsidiary"],
        },
        {
          type: "selectinput",
          tag: "selectinput",
          label: "Subsidiary*",
          name: "subsidiary",
          value: "",
          classvalue: {
            container: "col-span-12",

            label: "text-gray-600",
            field: "p-2",
          },
          required: true,
          options: [],
          dependency: "division",
          onChange: [
            {
              event: "updatechild",
            },
          ],
          fieldGrid: 1,
          displayOrder: 3,
          children: ["department"],
        },
        {
          type: "selectinput",
          tag: "selectinput",
          label: "Department*",
          name: "department",
          value: "",
          classvalue: {
            container: "col-span-12",
            label: "text-gray-600",
            field: "p-2",
          },
          required: true,
          options: [],
          dependency: "division",
          onChange: [
            {
              event: "updatechild",
            },
          ],
          fieldGrid: 1,
          displayOrder: 4,
          children: ["subdepartment"],
        },
        {
          type: "selectinput",
          tag: "selectinput",
          label: "Sub Department*",
          name: "subdepartment",
          value: "",
          classvalue: {
            container: "col-span-12",
            label: "text-gray-600",
            field: "p-2",
          },
          required: true,
          options: [],
          dependency: "department",
          onChange: [
            {
              event: "updatechild",
            },
          ],
          fieldGrid: 1,
          displayOrder: 5,
          children: ["section"],
        },
        {
          type: "selectinput",
          tag: "selectinput",
          label: "Section*",
          name: "section",
          value: "",
          classvalue: {
            container: "col-span-12",
            label: "text-gray-600",
            field: "p-2",
          },
          required: true,
          options: [],
          dependency: "division",
          onChange: [
            {
              event: "updatechild",
            },
          ],
          fieldGrid: 1,
          displayOrder: 6,
          children: [],
        },
      ],
    },
  ],
  actions: [
    {
      type: "button",
      label: "Select The Employee",
      action: "save",
      classvalue: "btn-primary px-8 rounded-lg w-full mt-4",
    },
  ],
};

export const diarectcontractoremployee = {
  component: "form",
  mode: "view",
  name: "",
  title: "",
  description: "",
  classvalue: "grid-cols-12",
  baseurl: "api/sectiondetails",
  subformstructure: [
    {
      formgrid: 1,
      title: "Diarect Selection",
      classvalue: "col-span-12 gap-4",
      validationRules: {
        required: [
          "code",
          "birth_date",
          "father_name",
          "owner_name",
          "owner_contact_no",
          "owner_email",
          "contact_person_name",
          "contact_person_contact_no",
          "contact_person_email",
          "type_of_company",
          "area_of_work",
          "service_from",
          "service_end",
          "name",
        ],
      },
      fields: [
        {
          type: "text",
          tag: "input",
          label: "Name *",
          value: "",

          classvalue: {
            container: "col-span-4 mb-2",
            label: "text-gray-600",
            field: "p-1",
          },
          name: "name",
          mode: "super-edit",
          required: false,
          icon: "",
          fieldgrid: 1,
          displayOrder: 2,
        },
        {
          type: "text",
          tag: "input",
          label: "Code",
          value: "",
          classvalue: {
            container: "col-span-4 mb-2",
            label: "text-gray-600",
            field: "p-1",
          },
          name: "code",
          mode: "super-edit",
          required: true,
          icon: "",
          fieldgrid: 1,
          displayOrder: 2,
        },
        {
          type: "checkbox",
          tag: "checkbox",
          label: "",
          value: "",
          name: "action",
          placeholder: "Enable quarter day option",
          classvalue: {
            container: "col-span-4 mb-2",
            label: "text-gray-600",
            field: "p-1",
          },
          required: false,
          mode: "super-edit",
          icon: "",
          fieldgrid: 1,
          displayOrder: 1,
        },
      ],
    },
  ],
  actions: [
    {
      type: "button",
      label: "Save",
      action: "save",
      classvalue: "btn-primary px-8 rounded-lg",
    },
    {
      type: "button",
      label: "Close",
      action: "close",
      classvalue: "btn-secondary bg-red-500 px-8 rounded-lg",
    },
  ],
};

export const selectfiltermode = {
  component: "form",
  mode: "view",
  name: "more",
  title: "contractor-employee",
  description:
    "Download the reports of all assigned contractor-employee records now.",
  classvalue: "grid-cols-12",
  baseurl: "api/sectiondetails",
  subformstructure: [
    {
      formgrid: 1,
      title: "Diarect Selection",
      classvalue: "col-span-12 gap-4",
      validationRules: {
        required: [
          "code",
          "birth_date",
          "father_name",
          "owner_name",
          "owner_contact_no",
          "owner_email",
          "contact_person_name",
          "contact_person_contact_no",
          "contact_person_email",
          "type_of_company",
          "area_of_work",
          "service_from",
          "service_end",
          "name",
        ],
      },
      fields: [
        {
          type: "select",
          tag: "select",
          label: "Report*",
          name: "report",
          value: "",
          classvalue: {
            container: "col-span-4 mb-2",
            label: "text-gray-600",
            field: "p-2",
          },
          required: true,
          options: [
            {
              label: "employee report",
              value: "employee-report",
              category: "construction",
            },
            {
              label: "employee pending detail report",
              value: "employee-pending-detail-report",
              category: "it services",
            },
            {
              label: "employee address report",
              value: "employee-address-report",
              category: "manufacturing",
            },
            {
              label: "employee experience func. edu. report",
              value: "employee-experience-func-edu-report",
              category: "education",
            },
            {
              label: "employee working location report",
              value: "employee-working-location-report",
              category: "healthcare",
            },
            {
              label: "employee assets report",
              value: "employee-assets-report",
              category: "construction",
            },
            {
              label: "employee ppe report",
              value: "employee-ppe-report",
              category: "it services",
            },
            {
              label: "employee application report",
              value: "employee-application-report",
              category: "manufacturing",
            },
            {
              label: "contractor employee family member report",
              value: "contractor-employee-family-member-report",
              category: "education",
            },
            {
              label: "employee area assign report",
              value: "employee-area-assign-report",
              category: "healthcare",
            },
            {
              label: "nominee details report",
              value: "nominee-details-report",
              category: "construction",
            },
            {
              label: "employee medical checkup history report",
              value: "employee-medical-checkup-history-report",
              category: "it services",
            },
            {
              label: "employee police verification history report",
              value: "employee-police-verification-history-report",
              category: "manufacturing",
            },
            {
              label: "employee disciplinary action report",
              value: "employee-disciplinary-action-report",
              category: "education",
            },
            {
              label: "employee history report",
              value: "employee-history-report",
              category: "healthcare",
            },
            {
              label: "user audit trail report",
              value: "user-audit-trail-report",
              category: "construction",
            },
            {
              label: "employee training report",
              value: "employee-training-report",
              category: "it services",
            },
            {
              label: "employee multiple work order report",
              value: "employee-multiple-work-order-report",
              category: "manufacturing",
            },
            {
              label: "employee work order details report",
              value: "employee-work-order-details-report",
              category: "education",
            },
            {
              label: "employee project salary report",
              value: "employee-project-salary-report",
              category: "healthcare",
            },
            {
              label: "employee card report",
              value: "employee-card-report",
              category: "construction",
            },
            {
              label: "covid vaccination report",
              value: "covid-vaccination-report",
              category: "it services",
            },
            {
              label: "employee count for billing report",
              value: "employee-count-for-billing-report",
              category: "manufacturing",
            },
          ],
          dependency: "",
          onChange: [
            {
              event: "updateChild",
            },
          ],
          fieldGrid: 1,
          displayOrder: 6,
          children: [],
        },
        {
          type: "select",
          tag: "select",
          label: "Mode of selection*",
          name: "section",
          value: "",
          classvalue: {
            container: "col-span-4 mb-2",
            label: "text-gray-600",
            field: "p-2",
          },
          required: true,

          options: [
            { label: "Diarect Selection", value: "diarect-selection" },
            { label: "Complex Selection", value: "complex-selection" },
          ],
          dependency: "division",
          onChange: [
            {
              event: "updateChild",
            },
          ],
          fieldGrid: 1,
          displayOrder: 6,
          children: [],
        },
        {
          type: "select",
          tag: "select",
          label: "Report Number*",
          name: "reportnumber",
          value: "",
          classvalue: {
            container: "col-span-4 mb-2",
            label: "text-gray-600",
            field: "p-2",
          },
          required: true,
          options: [
            { label: "One", value: "one" },
            { label: "More", value: "more" },
          ],
          dependency: "division",
          onChange: [
            {
              event: "updateChild",
            },
          ],
          fieldGrid: 1,
          displayOrder: 6,
          children: [],
        },
      ],
    },
  ],
  actions: [
    {
      type: "button",
      label: "Submit",
      action: "save",
      classvalue: "btn-primary px-8 rounded-lg",
    },
    // {
    //   type: "button",
    //   label: "Close",
    //   action: "close",
    //   classvalue: "btn-secondary bg-red-500 px-8 rounded-lg",
    // },
  ],
};

export const indivialfilter = {
  component: "form",
  mode: "view",
  title: "Generate Individual Report",
  description: "",
  classvalue: "grid-cols-12",
  baseurl: "api/sectiondetails",
  subformstructure: [
    {
      formgrid: 1,
      title: "",
      classvalue: "col-span-12 gap-4",
      validationRules: {
        required: [
          "code",
          "birth_date",
          "father_name",
          "owner_name",
          "owner_contact_no",
          "owner_email",
          "contact_person_name",
          "contact_person_contact_no",
          "contact_person_email",
          "type_of_company",
          "area_of_work",
          "service_from",
          "service_end",
          "name",
        ],
      },
      fields: [
        {
          type: "select",
          tag: "select",
          label: "Select the filteration key*",
          name: "filteration",
          icon: "building",
          mode: "super-edit",
          value: "",
          classvalue: {
            container: "col-span-12 mb-2",
            label: "text-gray-600",
            field: "p-2",
          },
          required: true,
          options: [
            { label: "Email", value: "emailfilter" },
            { label: "Name", value: "namefilter" },
            { label: "EMP Id", value: "empidfilter" },
          ],
          onChange: [
            {
              event: "updatechild",
            },
          ],
          fieldGrid: 1,
          displayOrder: 1,
          children: ["empfilter"],
        },
        {
          type: "text",
          tag: "input",
          label: "Employee Filter",
          name: "empfilter",
          value: "",
          classvalue: {
            container: "col-span-12 mb-2",
            label: "text-gray-600",
            field: "p-2",
          },
          required: true,
          mode: "view",
          optionsrules: ["emailfilter", "namefilter", "empidfilter"],
          options: [],
          onChange: [
            {
              event: "updatechild",
            },
          ],
          fieldGrid: 1,
          displayOrder: 2,
          children: ["empfilters"],
        },
        {
          type: "radiobutton",
          tag: "radiobutton",
          label: "Select the filteration value",
          value: "",
          name: "empfilters",
          mode: "super-edit",
          classvalue: {
            container: "col-span-12 mb-2",
            label: "text-gray-600",
            field: "p-2",
          },
          main: true,
          icon: "",
          optionsrules: [
            "emailfilter",
            "namefilter",
            "empidfilter",
            "updatevalue",
          ],
          options: [],
          onChange: [
            {
              event: "",
            },
          ],
          required: true,
          fieldgrid: 1,
          displayOrder: 3,
        },
      ],
    },
  ],
  actions: [
    {
      type: "button",
      label: "Continue",
      action: "continue",
      classvalue: "btn-primary w-full",
    },
  ],
};
