export enum FormFieldEnum {
    TEXT = "text",
    TEXTAREA = "textarea",
    PASSWORD = "password",
    EMAIL = "email",
    NUMBER = "number",
    CHECKBOX = "checkbox",
    RADIO = "radio",
    SELECT = "select",
    DATE = "date",
    TIME = "time",
    DATETIME = "datetime-local",
    FILE = "file",
    HIDDEN = "hidden",
    TEL = "tel",
    URL = "url",
    RANGE = "range",
    COLOR = "color",
    SEARCH = "search",
    SWITCH = "switch",
    MULTISELECT = "multiselect"
}
export enum ModeEnum {
    VIEW = "view",
    SAVE = "save",
    UPDATE = "update",
    DELETE = "delete",
    SUPEREDIT = "super-edit",
    DISABLED="disabled",
    NONE = "none", 
  }