export const employerData = [
    {
        _id: "1",
        employerName: "Tech Solutions Inc",
        registrationNumber: "REG123456",
        taxId: "TAX789012",
        industry: "Information Technology",
        employeeCount: "250",
        foundedYear: "2010",
        annualRevenue: "5000000",
        address: "123 Tech Park, Silicon Valley",
        city: "San Francisco",
        state: "CA",
        country: "USA",
        postalCode: "94105",
        contactPerson: "John Smith",
        contactEmail: "john@techsolutions.com",
        contactPhone: "+1-555-0123",
        website: "www.techsolutions.com",
        businessType: "Corporation",
        ownershipType: "Private",
        complianceStatus: "Compliant",
        lastAuditDate: "2024-01-15",
        certifications: "ISO 9001, ISO 27001",
        benefits: "Health, Dental, 401K",
        workCulture: "Innovative",
        remotePolicy: "Hybrid",
        officeLocations: "3",
        trainingPrograms: "Yes",
        diversityScore: "85",
        employeeRetention: "92%",
        marketPosition: "Leader",
        growthRate: "15%",
        sustainabilityScore: "88",
        socialMedia: {
            linkedin: "linkedin.com/company/techsolutions",
            twitter: "@techsolutions",
            facebook: "facebook.com/techsolutions"
        },
        techStack: ["React", "Node.js", "AWS", "Python"],
        fundingRound: "Series B",
        investors: ["Sequoia Capital", "Andreessen Horowitz"],
        patentCount: "12",
        researchBudget: "1000000"
    },
    {
        _id: "2",
        employerName: "Global Manufacturing Co",
        registrationNumber: "REG789012",
        taxId: "TAX345678",
        industry: "Manufacturing",
        employeeCount: "1200",
        foundedYear: "1995",
        annualRevenue: "15000000",
        address: "456 Industrial Zone",
        city: "Detroit",
        state: "MI",
        country: "USA",
        postalCode: "48201",
        contactPerson: "Sarah Johnson",
        contactEmail: "sarah@globalmfg.com",
        contactPhone: "+1-555-0124",
        website: "www.globalmfg.com",
        businessType: "Corporation",
        ownershipType: "Public",
        complianceStatus: "Compliant",
        lastAuditDate: "2024-02-01",
        certifications: "ISO 9001, ISO 14001",
        benefits: "Full Benefits Package",
        workCulture: "Traditional",
        remotePolicy: "On-site",
        officeLocations: "5",
        trainingPrograms: "Yes",
        diversityScore: "78",
        employeeRetention: "88%",
        marketPosition: "Established",
        growthRate: "8%",
        sustainabilityScore: "82",
        socialMedia: {
            linkedin: "linkedin.com/company/globalmfg",
            twitter: "@globalmfg",
            facebook: "facebook.com/globalmfg"
        },
        techStack: ["SAP", "Oracle", "IoT", "Robotics"],
        fundingRound: "IPO",
        investors: ["Public Markets"],
        patentCount: "45",
        researchBudget: "5000000"
    },
    {
        _id: "3",
        employerName: "Healthcare Partners LLC",
        registrationNumber: "REG345678",
        taxId: "TAX901234",
        industry: "Healthcare",
        employeeCount: "800",
        foundedYear: "2005",
        annualRevenue: "12000000",
        address: "789 Medical Center Dr",
        city: "Boston",
        state: "MA",
        country: "USA",
        postalCode: "02108",
        contactPerson: "Dr. Michael Brown",
        contactEmail: "michael@healthcarepartners.com",
        contactPhone: "+1-555-0125",
        website: "www.healthcarepartners.com",
        businessType: "LLC",
        ownershipType: "Private",
        complianceStatus: "Compliant",
        lastAuditDate: "2024-01-20",
        certifications: "JCI, ISO 9001",
        benefits: "Comprehensive Healthcare",
        workCulture: "Patient-Centric",
        remotePolicy: "Flexible",
        officeLocations: "8",
        trainingPrograms: "Yes",
        diversityScore: "92",
        employeeRetention: "95%",
        marketPosition: "Leading",
        growthRate: "12%",
        sustainabilityScore: "90",
        socialMedia: {
            linkedin: "linkedin.com/company/healthcarepartners",
            twitter: "@healthcarepartners",
            facebook: "facebook.com/healthcarepartners"
        },
        techStack: ["Epic", "Cerner", "AI/ML", "Telehealth"],
        fundingRound: "Series C",
        investors: ["Kaiser Permanente", "Mayo Clinic"],
        patentCount: "8",
        researchBudget: "3000000"
    },
    {
        _id: "4",
        employerName: "Green Energy Solutions",
        registrationNumber: "REG567890",
        taxId: "TAX234567",
        industry: "Renewable Energy",
        employeeCount: "450",
        foundedYear: "2015",
        annualRevenue: "8000000",
        address: "321 Solar Street",
        city: "Austin",
        state: "TX",
        country: "USA",
        postalCode: "78701",
        contactPerson: "Emma Wilson",
        contactEmail: "emma@greenenergy.com",
        contactPhone: "+1-555-0126",
        website: "www.greenenergy.com",
        businessType: "Corporation",
        ownershipType: "Private",
        complianceStatus: "Compliant",
        lastAuditDate: "2024-02-15",
        certifications: "ISO 14001, LEED",
        benefits: "Green Benefits Package",
        workCulture: "Sustainable",
        remotePolicy: "Hybrid",
        officeLocations: "4",
        trainingPrograms: "Yes",
        diversityScore: "88",
        employeeRetention: "90%",
        marketPosition: "Emerging",
        growthRate: "25%",
        sustainabilityScore: "95",
        socialMedia: {
            linkedin: "linkedin.com/company/greenenergy",
            twitter: "@greenenergy",
            facebook: "facebook.com/greenenergy"
        },
        techStack: ["Solar Tech", "Wind Power", "Smart Grid", "IoT"],
        fundingRound: "Series A",
        investors: ["Clean Energy Fund", "Green Ventures"],
        patentCount: "15",
        researchBudget: "2000000"
    },
    {
        _id: "5",
        employerName: "FinTech Innovations",
        registrationNumber: "REG901234",
        taxId: "TAX567890",
        industry: "Financial Technology",
        employeeCount: "300",
        foundedYear: "2018",
        annualRevenue: "6000000",
        address: "789 Wall Street",
        city: "New York",
        state: "NY",
        country: "USA",
        postalCode: "10005",
        contactPerson: "David Chen",
        contactEmail: "david@fintechinnovations.com",
        contactPhone: "+1-555-0127",
        website: "www.fintechinnovations.com",
        businessType: "Corporation",
        ownershipType: "Private",
        complianceStatus: "Compliant",
        lastAuditDate: "2024-02-10",
        certifications: "ISO 27001, PCI DSS",
        benefits: "Financial Wellness Package",
        workCulture: "Fast-Paced",
        remotePolicy: "Remote-First",
        officeLocations: "2",
        trainingPrograms: "Yes",
        diversityScore: "82",
        employeeRetention: "85%",
        marketPosition: "Disruptor",
        growthRate: "35%",
        sustainabilityScore: "75",
        socialMedia: {
            linkedin: "linkedin.com/company/fintechinnovations",
            twitter: "@fintechinnovations",
            facebook: "facebook.com/fintechinnovations"
        },
        techStack: ["Blockchain", "AI/ML", "Cloud", "Cybersecurity"],
        fundingRound: "Series B",
        investors: ["Goldman Sachs", "JP Morgan"],
        patentCount: "6",
        researchBudget: "1500000"
    }
]; 