export const subsidiary = {
  component: "form",
  mode: "view",
  title: "Subsidiary",
  description:
    "An subsidiary is a structured group working toward shared goals.",
  classvalue: "grid-cols-12",
  baseurl: "api/sectiondetails",
  subformstructure: [
    {
      formgrid: 1,
      title: "Details",
      classvalue: "col-span-6 gap-4",
      validationRules: {
        required: [
          "code",
          "birth_date",
          "father_name",
          "owner_name",
          "owner_contact_no",
          "owner_email",
          "contact_person_name",
          "contact_person_contact_no",
          "contact_person_email",
          "type_of_company",
          "area_of_work",
          "service_from",
          "service_end",
          "name",
        ],
      },
      fields: [
        {
          type: "text",
          tag: "input",
          label: "Name *",
          value: "",

          classvalue: {
            container: "col-span-6 mb-2",
            label: "text-gray-600",
            field: "p-1",
          },
          name: "name",
          mode: "super-edit",
          required: false,
          icon: "",
          fieldgrid: 1,
          displayOrder: 1,
        },
        {
          type: "text",
          tag: "input",
          label: "Code",
          value: "",
          classvalue: {
            container: "col-span-6 mb-2",
            label: "text-gray-600",
            field: "p-1",
          },
          name: "code",
          mode: "super-edit",
          required: true,
          icon: "",
          fieldgrid: 1,
          displayOrder: 2,
        },
        {
          type: "textarea",
          tag: "textarea",
          label: "Description",
          classvalue: {
            container: "col-span-12 mb-2",
            label: "text-gray-600",
            field: "p-1",
          },
          name: "description",
          mode: "super-edit",
          required: true,
          icon: "",
          fieldgrid: 1,
          displayOrder: 3,
        },
        {
          type: "checkbox",
          tag: "checkbox",
          label: "",
          value: "",
          name: "action",
          placeholder: "Enable quarter day option",
          classvalue: {
            container: "col-span-6 mb-2",
            label: "text-gray-600",
            field: "p-1",
          },
          required: false,
          mode: "super-edit",
          icon: "",
          fieldgrid: 1,
          displayOrder: 3,
        },
      ],
    },
    {
      formgrid: 1,
      classvalue: "col-span-6 ",
      title: "Contact Detail",
      validationRules: {
        required: [
          "code",
          "birth_date",
          "father_name",
          "owner_name",
          "owner_contact_no",
          "owner_email",
          "contact_person_name",
          "contact_person_contact_no",
          "contact_person_email",
          "type_of_company",
          "area_of_work",
          "service_from",
          "service_end",
          "name",
        ],
      },
      fields: [
        {
          type: "text",
          tag: "input",
          label: "Contact (P)",
          value: "",
          classvalue: {
            container: "col-span-12 mb-2",
            label: "text-gray-600",
            field: "p-1",
          },
          name: "addresslineone",
          mode: "super-edit",
          required: true,
          icon: "",
          fieldgrid: 1,
          displayOrder: 1,
        },
        {
          type: "text",
          tag: "input",
          label: "Contact (S)",
          value: "",
          classvalue: {
            container: "col-span-12 mb-2",
            label: "text-gray-600",
            field: "p-1",
          },
          name: "addresslinetwo",
          mode: "super-edit",
          required: true,
          icon: "",
          fieldgrid: 1,
          displayOrder: 2,
        },
        {
          type: "text",
          tag: "input",
          label: "Email Id",
          value: "",
          classvalue: {
            container: "col-span-6 mb-2",
            label: "text-gray-600",
            field: "p-1",
          },
          name: "city",
          mode: "super-edit",
          required: true,
          icon: "",
          fieldgrid: 1,
          displayOrder: 4,
        },
        {
          type: "text",
          tag: "input",
          label: "Website",
          value: "",
          classvalue: {
            container: "col-span-6 mb-2",
            label: "text-gray-600",
            field: "p-1",
          },
          name: "pincode",
          mode: "super-edit",
          required: true,
          icon: "",
          fieldgrid: 1,
          displayOrder: 4,
        },
        {
          type: "radiobutton",
          tag: "radiobutton",
          label: "Select the filteration value",
          value: "",
          name: "empfilters",
          mode: "super-edit",
          classvalue: {
            container: "col-span-12 mb-2",
            label: "text-gray-600",
            field: "p-2",
          },
          main: true,
          icon: "",
          optionsrules: [
            "emailfilter",
            "namefilter",
            "empidfilter",
            "updatevalue",
          ],
          options: [
            { label: "Email", value: "emailfilter" },
            { label: "Name", value: "namefilter" },
            { label: "EMP Id", value: "empidfilter" },
          ],
          onChange: [
            {
              event: "",
            },
          ],
          required: true,
          fieldgrid: 1,
          displayOrder: 3,
        },
      ],
    },
  ],
  actions: [
    {
      type: "button",
      label: "Save",
      action: "save",
      classvalue: "btn-primary",
    },
    {
      type: "button",
      label: "Close",
      action: "close",
      classvalue: "btn-secondary",
    },
    {
      type: "button",
      label: "Submit",
      action: "submit",
      classvalue: "btn-secondary",
    },
  ],
};

export const headData = [
  "name",
  "code",
  "region",
  "zone",
  "active",
  "address_line_1",
  "address_line_2",
  "country*",
  "state",
  "city*",
  "pincode",
];
