// data/leavePolicy.js

export const leavePolicy = [
    {
      title: "Annual Leave",
      leaveCode: "AL001",
      effectiveFrom: "2025-01-01",
      active: true,
      applicabilityGender: "All",
      maritalStatus: "Single, Married",
      minServicePeriod: 0,
      maxLeavePerYear: 20,
      minDaysPerApp: 1,
      maxDaysPerApp: 10,
      halfDayAllowed: true,
      sandwichHolidayCounted: false,
      sandwichWeeklyOffCounted: false,
      startEndOnHoliday: true,
      startEndOnWeeklyOff: true,
      autoApprovalDays: 5,
      accrualType: "Monthly",
      carryForwardLimit: 30,
      encashmentAllowed: true,
      maxEncashmentPerYear: 2
    },
    {
      title: "Sick Leave",
      leaveCode: "SL001",
      effectiveFrom: "2025-01-01",
      active: true,
      applicabilityGender: "All",
      maritalStatus: "All",
      minServicePeriod: 0,
      maxLeavePerYear: 10,
      minDaysPerApp: 1,
      maxDaysPerApp: 5,
      halfDayAllowed: true,
      sandwichHolidayCounted: true,
      sandwichWeeklyOffCounted: true,
      startEndOnHoliday: true,
      startEndOnWeeklyOff: true,
      autoApprovalDays: 3,
      accrualType: "Monthly",
      carryForwardLimit: 15,
      encashmentAllowed: false,
      maxEncashmentPerYear: 0
    },
    {
      title: "Maternity Leave",
      leaveCode: "ML001",
      effectiveFrom: "2025-01-01",
      active: true,
      applicabilityGender: "F",
      maritalStatus: "All",
      minServicePeriod: 365,
      maxLeavePerYear: 90,
      minDaysPerApp: 30,
      maxDaysPerApp: 90,
      halfDayAllowed: false,
      sandwichHolidayCounted: false,
      sandwichWeeklyOffCounted: false,
      startEndOnHoliday: false,
      startEndOnWeeklyOff: false,
      autoApprovalDays: 0,
      accrualType: "None",
      carryForwardLimit: 0,
      encashmentAllowed: false,
      maxEncashmentPerYear: 0
    },
    {
      title: "Paternity Leave",
      leaveCode: "PL001",
      effectiveFrom: "2025-01-01",
      active: true,
      applicabilityGender: "M",
      maritalStatus: "Married",
      minServicePeriod: 180,
      maxLeavePerYear: 10,
      minDaysPerApp: 2,
      maxDaysPerApp: 10,
      halfDayAllowed: false,
      sandwichHolidayCounted: false,
      sandwichWeeklyOffCounted: false,
      startEndOnHoliday: false,
      startEndOnWeeklyOff: false,
      autoApprovalDays: 2,
      accrualType: "None",
      carryForwardLimit: 0,
      encashmentAllowed: false,
      maxEncashmentPerYear: 0
    },
    {
      title: "Unpaid Leave",
      leaveCode: "UL001",
      effectiveFrom: "2025-01-01",
      active: true,
      applicabilityGender: "All",
      maritalStatus: "All",
      minServicePeriod: 0,
      maxLeavePerYear: 999,
      minDaysPerApp: 1,
      maxDaysPerApp: 30,
      halfDayAllowed: true,
      sandwichHolidayCounted: true,
      sandwichWeeklyOffCounted: true,
      startEndOnHoliday: true,
      startEndOnWeeklyOff: true,
      autoApprovalDays: 10,
      accrualType: "None",
      carryForwardLimit: 0,
      encashmentAllowed: false,
      maxEncashmentPerYear: 0
    },
    {
      title: "Compensatory Off",
      leaveCode: "CO001",
      effectiveFrom: "2025-01-01",
      active: true,
      applicabilityGender: "All",
      maritalStatus: "All",
      minServicePeriod: 0,
      maxLeavePerYear: 15,
      minDaysPerApp: 0.5,
      maxDaysPerApp: 2,
      halfDayAllowed: true,
      sandwichHolidayCounted: false,
      sandwichWeeklyOffCounted: false,
      startEndOnHoliday: true,
      startEndOnWeeklyOff: true,
      autoApprovalDays: 2,
      accrualType: "Quarterly",
      carryForwardLimit: 5,
      encashmentAllowed: false,
      maxEncashmentPerYear: 0
    },
    {
      title: "Bereavement Leave",
      leaveCode: "BL001",
      effectiveFrom: "2025-01-01",
      active: true,
      applicabilityGender: "All",
      maritalStatus: "All",
      minServicePeriod: 0,
      maxLeavePerYear: 5,
      minDaysPerApp: 1,
      maxDaysPerApp: 5,
      halfDayAllowed: false,
      sandwichHolidayCounted: false,
      sandwichWeeklyOffCounted: false,
      startEndOnHoliday: false,
      startEndOnWeeklyOff: false,
      autoApprovalDays: 1,
      accrualType: "None",
      carryForwardLimit: 0,
      encashmentAllowed: false,
      maxEncashmentPerYear: 0
    },
    {
      title: "Marriage Leave",
      leaveCode: "MRL001",
      effectiveFrom: "2025-01-01",
      active: true,
      applicabilityGender: "All",
      maritalStatus: "Single",
      minServicePeriod: 180,
      maxLeavePerYear: 5,
      minDaysPerApp: 2,
      maxDaysPerApp: 5,
      halfDayAllowed: false,
      sandwichHolidayCounted: false,
      sandwichWeeklyOffCounted: false,
      startEndOnHoliday: true,
      startEndOnWeeklyOff: true,
      autoApprovalDays: 3,
      accrualType: "Yearly",
      carryForwardLimit: 0,
      encashmentAllowed: false,
      maxEncashmentPerYear: 0
    },
    {
      title: "Study Leave",
      leaveCode: "STL001",
      effectiveFrom: "2025-01-01",
      active: false,
      applicabilityGender: "All",
      maritalStatus: "All",
      minServicePeriod: 365,
      maxLeavePerYear: 30,
      minDaysPerApp: 5,
      maxDaysPerApp: 30,
      halfDayAllowed: false,
      sandwichHolidayCounted: true,
      sandwichWeeklyOffCounted: true,
      startEndOnHoliday: false,
      startEndOnWeeklyOff: false,
      autoApprovalDays: 7,
      accrualType: "None",
      carryForwardLimit: 0,
      encashmentAllowed: false,
      maxEncashmentPerYear: 0
    },
    {
      title: "Special Leave",
      leaveCode: "SPL001",
      effectiveFrom: "2025-01-01",
      active: true,
      applicabilityGender: "All",
      maritalStatus: "All",
      minServicePeriod: 90,
      maxLeavePerYear: 7,
      minDaysPerApp: 1,
      maxDaysPerApp: 7,
      halfDayAllowed: false,
      sandwichHolidayCounted: true,
      sandwichWeeklyOffCounted: false,
      startEndOnHoliday: true,
      startEndOnWeeklyOff: false,
      autoApprovalDays: 4,
      accrualType: "Quarterly",
      carryForwardLimit: 10,
      encashmentAllowed: true,
      maxEncashmentPerYear: 1
    }
  ];
  
  export default leavePolicy;
  